name: abastecimentoflutter
description: A new Flutter project.

# Prevenção de publicação acidental no pub.dev
publish_to: 'none'

# Versão da aplicação
version: 1.0.0+1

# Configuração de ambiente
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependências principais
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.5
  mask_text_input_formatter: ^2.9.0
  flutter_date_pickers: ^0.4.3
  intl: ^0.19.0

# Dependências de desenvolvimento
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Configurações específicas do Flutter
flutter:
  uses-material-design: true

  # Ativando o uso de recursos estáticos (imagens, ícones, etc.)s
